server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zabbix
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    name: zabbix
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      dialect: org.hibernate.dialect.MySQL5Dialect
banner:
  charset: utf-8
  location: banner.txt
#debug: true